language: node_js

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - apt-get update -qq
  - apt-get install -y build-essential curl git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev
  - "brew install watchman"
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
