language: node_js

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - "brew install watchman"
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
